### ISSUE TITLE
Grow graph from selected nodes

### ISSUE THREAD

**Issue by heatherleaf** [comparative-concepts/cc-database#11]
Currently the Grow buttons (upwards, downwards, outwards) grow from all currently visible graph nodes. 

It would be better to grow only from selected nodes. 

Question to @wcroft : if no nodes are selected, should it still be possible to grow the graph (and then it would work as now)? Or should the Grow buttons be greyed out?

**Comment by wcroft** [comment]
I agree it would be better to grow only from selected nodes.

I think we should still allow growing the entire graph as it is now. But maybe for consistency (at least to the user), we could include a Select All button, and if the user wants to grow out the entire subgraph, they can Select All and then use the current Grow buttons. That way the user will always be growing from selected nodes.

**Comment by heatherleaf** [comment]
I agree that a Select All button is the best

**Comment by heatherleaf** [comment]
Added a button to select "all visible", and only grow from selected nodes, in https://github.com/comparative-concepts/cc-database/commit/40ad2d02e2189bd3fb13f82e628c40611354aff8

**Comment by wcroft** [comment]
@heatherleaf - now that I have used the revised Grow function, I am thinking that maybe the original function was better for most users, and even myself. The revised Grow function grows from selected nodes, but the selection doesn't change. Depending on what the user wants to do, they have to select another subset. I thought of suggesting that the revised Grow function selects all the added nodes. But I am now thinking that most users will use the Grow function to explore the network which will be unfamiliar with them. (My test exercise was to grow the graph to a predetermined tree, namely Tree 5 of the Construction Relations trees. Few people will do that sort of exercise.) As users explore the network to find the part they're interested in, using the original Grow function, they will prune away whatever they don't want to look at.

I'm not sure the original Grow function is the best solution, but I think maybe it's best to go back to it, and let other users tell us what would be an improvement.

**Comment by heatherleaf** [comment]
The original grow function is the same as first "select all" and then "grow" in the new setup, but at the same time you have the possibility to be more specific. I kind of like the new possibility...

One option would be to let "grow" mean the same as before if no nodes are selected, otherwise grow from selected nodes.

But if the use case is that you want to keep a selection independently of growing the graph, then it's not possible with the new setup. On the other hand, to remove nodes you definitely have to change the selection.

**Comment by wcroft** [comment]
I like the option of letting "grow" mean the same as before if no nodes are selected, otherwise grow from selected nodes.
I would support making this change and keeping the revised "grow" function. I think that only more practice with using "grow" will let us figure out the best implementation.

**Comment by heatherleaf** [comment]
Ok, did it with a twist, in d0b1a49b0196f039365e3d684d90cad9ffa8be17.

If the selection is empty then it selects all nodes and then grows the graph. This means that afterwards the selection is the previous graph, which makes it possible to do a "one-step" undo: if you're not satisfied you can "remove unselected" and you're back to the graph you had before.

However, this means that you can't click "grow" several times in a row, because the second time you have a selection which it tries to grow from. So you have to unselect everything and then click "grow".

Try it out. If you don't like it I can skip the selection step (so that if nothing is selected then the graph with just grow and nothing will be selected).

**Comment by wcroft** [comment]
I think that actually it is better without the twist. I think that in exploring the graph, gorwing multiple times will happen often so not having to select all first is simpler. Also, if you want to select just a node or two and expand just those, it's the same whether all of the previous nodes were selected or none of them are. 
It's true that your twist allows a sort of "undo". But I'm hoping that eventually you'll be able to implement a general undo function.

**Comment by heatherleaf** [comment]
Ok, I removed the twist.

**Comment by heatherleaf** [comment]
Closing this now, but you can open a new issue if you come up with new ideas how to modify the graph
