### ISSUE TITLE
Cxn -> Str graph updates

### ISSUE THREAD

**Issue by wcroft** [comparative-concepts/cc-database#7]
I have gone through the Cxn -> Str graph as best as I could. It is so large that I may have missed somethings, but there are a couple of corrections, and revisions to the (dis)alignment strategies, beyond what I wrote to Arthur earlier (Jan 7 2024 email).

In that email, I renamed the oblique P strategy in the Glossary, for the antipassive as "P alignment", i.e. whether P in a bivalent event, which is encoded as object in the (basic voice) transitive construction, is encoded (sort of) like an oblique or not ("not" means "like it is in basic voice"). Conversely, I also named the applicative strategy "oblique alignment", i.e. whether a participant role encoded as oblique in basic voice, is encoded (sort of) like an object or not ("not" means "like it is in basic voice").

However, I didn't do anything about what I called the subject-oblique strategy in the book. I intended to get rid of it, but I see that I left it in the Strategy trees as a strategy for the participant in an experiential construction that is not coded as subject in either the experiencer-oriented strategy (subject = experiencer) or the stimulus-oriented strategy (subject = stimulus). The nonsubject argument (stimulus or experiencer respectively) can be expressed either like an object in basic voice, or like an oblique in basic voice. This is basically the alternative alignments found in "P alignment": given that one participant is aligned to be like a subject, the other participant is aligned to look (sort of) like an object or an oblique.

So I have decided to merge what were originally oblique P strategy and subject-oblique strategy. But I can't call this merged strategy "P alignment", because the nonsubject argument in the experiential construction is not a P. And the other constructions using the subject-oblique strategy encode events whose second most prominent participant is not a prototypical P either ("lower transitivity events"). So I have decided to (re)name the merged strategy, "object alignment", on analogy with "oblique alignment":

- object alignment: how the P or other most salient nonsubject argument, coded as object in the basic voice transitive construction, is coded, i.e. (more) object-like or (more) oblique-like
- oblique alignment: how the peripheral participant, coded as oblique in the basic voice construction, is coded, i.e. (more) object-like or (more) oblique-like
- (the parenthetical hedges are because many constructions use a strategy where different coding strategies -- word order, flagging, indexation -- may not all treat the argument in question in the same way)

NB: for both object alignment and oblique alignment, the coding unlike basic voice is not subject-like coding. That would be part of A/P alignment. The name "A/P alignment" is something of a misnomer; maybe I should call it "subject-object alignment", to show that it applies to both subject and object alignment. Though there are cases of obliques becoming subjects: Japanese passive can passivize obliques; in some Bantu language you can make a peripheral participant subject with an applicative affix plus a passive affix; even in English you can say "This bed was slept in by George Washington". So maybe "subject-nonsubject alignment" is a better name. But it's also a long name. In addition, there was a long debate long ago about whether passive voice was "really" just "subject-demotion" or "object promotion". But it's a continuum in both directions--that is, either or both A and non-A arguments may become (sort of) non-subject and (sort of) subject respectively. So a name like "subject alignment" is therefore also a bit misleading.

All these names -- object alignment, oblique alignmnet, A/P alignment -- could be changed again, since none are in the book or the glossary. But for now, I'll stick with "A/P alignment", "object alignment" and "oblique alignment". So these are the concrete changes to be made here:

- Merge P alignment (ex oblique P strategy) and subject-object strategy; rename as object alignment
- object alignment SubtypeOf alignment system, NOT SubtypeOf system

(I should also mention that nearly all systems of strategies are alignment systems. This category of strategies might be reviewed in the future.)

The remaining are minor fixes:

- verbal copula strategy preferred name to verbal copula
- str:verbal-copula-strategy ExpressionOf nonprototypical-predication, NOT ExpressionOf cxn:predicational-location-construction
- str:satellite ExpressionOf cxn:motion-argument-structure-construction
- [This last is following the general principle of making strategies pertaining to parts of a constructions to be strategies of the construction as a whole]

All these changes are reflected in the updated Strategy Trees now on Github.

**Comment by arthurlorenzi** [comment]
@wcroft I've made the changes and will close the issue. If you still find any problem in the strategy trees, just reopen this one. Thanks!

**Comment by wcroft** [comment]
OK, I trust it’s all good now. If I come across something, I’ll reopen the issue. (How do you reopen an issue?)

I presume you’re moving on to FunctionOf relations?

Bill

**Comment by arthurlorenzi** [comment]
Yes, I'm moving to the FunctionOf relations!

To reopen an issue you just need to comment on it. When you write your comment you'll see two options "comment" or "reopen with comment".
